= Oracle stored procedure client sample application

:important-caption: :heavy_exclamation_mark:

== Introducción

Este es un ejemplo de diferentes formas de invocar lógicas de negocio en Oracle a través de JDBC utilizando:

* *JDBC*: estándar de java sin utilizar librerías externas.
* *Spring JDBC*: ejemplo de uso de la clase `SimpleJdbcCall` de Spring Data para simplificar las operaciones JDBC.
* *Spring Oracle*: librería descontinuada de Spring para Oracle.
* *JPA*: acceso directo a las tablas sin utilizar las lógicas de negocio de Oracle.

En este ejemplo veremos:

* Ejemplos de acceso utilizando procedimientos almacenados
* Ejemplos de acceso utilizando funciones.
* Comportamiento con beans con estructuras anidadas complejas. 

Nuestro modelo será muy sencillo. Tendremos por un lado un CRUD de una entidad sencilla (id, nombre
y descripción) con una serie de funciones de Oracle:

* __f_get__: lectura.
* __f_inr__: inserción.
* __f_upd__: actualización.
* __f_del__: eliminación.

Por otro lado tendremos la entidad _Claim_ correspodiente a un objeto que representa la información
de un siniestro que tendrá una estructura anidada de entidades complejas.

== Participantes

Nuestro objeto de negocio será:

[source,java]
----
@Entity
@Table(name = "MPD_GEN_PARTICIPANTE")
@Getter
@Setter
public class Participant {

  public static final String ORACLE_TYPE_NAME = "O_AMD_GNL_PAR_S";
  public static final String ORACLE_LIST_NAME = "O_AMD_GNL_PAR_ST";

  @Id
  @Column(name = "COD_PART_PROC")
  @OracleField("par_prc_prc_val")
  private Long id;

  @Column(name = "NOM_PART_PROC")
  @OracleField("nam_par_prc")
  private String name;

  @Column(name = "DES_PART_PROC")
  @OracleField("dsp_par_prc")
  private String description;
}
----

Vemos que esta entidad tiene dos tipos de anotaciones:

* *Anotaciones de JPA* que hacen referencia a la tabla _MPD_GEN_PARTICIPANTE_.
* *Anotaciones propias de la aplicación*: que hacen referencia al tipo de Oracle _O_AMD_GNL_PAR_S_.

En este caso combinaremos las anotaciones para mostrar cómo una misma entidad puede utilizarse tanto
para el acceso directo a la tabla de Oracle utilizando JPA como para el acceso a través de tipos de
Oracle utilizando procedimientos almacenados y funciones.

=== Acceso utilizando Spring Oracle

Una de las piedras angulares de la librería es la interface
https://github.com/spring-projects/spring-data-jdbc-ext/blob/master/spring-data-oracle/src/main/java/org/springframework/data/jdbc/support/oracle/StructMapper.java[StructMapper].
Esta interface establece cómo se establecen los mapeos de _STRUCTS_ de Oracle a entidades de Java y
viceversa.

La librería de Spring define la implementación
https://github.com/spring-projects/spring-data-jdbc-ext/blob/master/spring-data-oracle/src/main/java/org/springframework/data/jdbc/support/oracle/BeanPropertyStructMapper.java[BeanPropertyStructMapper]
que utiliza la API de reflexión de Java con ciertas limitaciones que veremos más adelante. No
obstante podemos extender esta clase o trabajar con nuestra implementación de _StructMapper_.

En este caso *para cada procedimiento almacenado tendremos que extender* la clase
`org.springframework.jdbc.object.StoredProcedure` (incluso en el caso de que
estemos invocando una función de Oracle en lugar de un procedimiento almacenado) del siguiente modo:

[source,java]
----
public class ParticipantOracleReadProcedure extends ParticipantStoredProcedure {

  private static final String FUNCTION_NAME = "dl_gnl_par.f_get";

  public ParticipantOracleReadProcedure(DataSource dataSource, StructMapperService mapperService) {
    super(dataSource, FUNCTION_NAME, mapperService);
    SqlReturnArray sqlReturn = new SqlListStructArray<>(mapperService.mapper(Participant.class));
    setFunction(true);
    declareParameter(new SqlOutParameter("return", Types.ARRAY, Participant.ORACLE_LIST_NAME, sqlReturn));
    declareParameter(new SqlParameter("p_o_amd_gnl_par_s", Types.STRUCT, Participant.ORACLE_TYPE_NAME));
    compile();
  }

  @SuppressWarnings("unchecked")
  public List<Participant> find(Participant beanQuery) {
    StructMapper<Participant> mapper = mapperService.mapper(Participant.class);
    SqlStructValue<Participant> structValue = new SqlStructValue<>(beanQuery, mapper);
    Map<String, Object> resultMap = super.execute(structValue);
    return (List<Participant>) resultMap.get("return");
  }
}
----

Siendo `ParticipantStoredProcedure` una clase que extiende de `StoredProcedure` en la que
simplemente definimos nuestro componente para obtener el `StructMapper` asociado a una determinada
entidad:

[source,java]
----
public class ParticipantStoredProcedure extends StoredProcedure {

  protected StructMapperService mapperService;

  public ParticipantStoredProcedure(DataSource dataSource, String storedProcedureName,
    StructMapperService mapperService) {

    super(dataSource, storedProcedureName);
    this.mapperService = mapperService;
  }

}
----

Vemos que básicamente tenemos que declarar los parámetros de entrada y salida y establecer los
mapeadores de tipos.

En el caso de las funciones con participantes trabajaremos con nuestra propia implementación de
`StructMapper` basada en anotaciones:

[source,java]
----
public class AnnotationStructMapper<T> implements StructMapper<T> { ... }
----

Esta implementación se basa en la utilización de nuestra anotación `@OracleField` de un modo similar
a la anotación `@Column` de JPA que utilizaremos para mapear los tipos de una entidad con el objeto
`STRUCT` del driver de Oracle.


== Siniestros

=== Acceso utilizando Spring Oracle

En este caso en lugar de trabajar con el `StructMapper` anterior basado en anotaciones trabajaremos
con una versión extendida de la que ofrece la librería de Spring.

En este caso hemos realizado algunas pequeñas adaptaciones:

* Utilizar un servicio para obtener los descriptores. Esto lo hacemos para evitar que para cada
conversión de tipos consulte a la base de datos para obtener la estructura. Dado que el resultado
es un `Serializable` podemos almacenar en memoria está información mejorando considerablemente el
rendimiento en la aplicación.

* Adaptar el mapedor para permitir la conversión de tipos anidados. En la librería original no tiene
en cuenta a la hora de montar el array de elementos que estos a su vez pueden ser de tipo _STRUCT_
en lugar de tipos básicos. En este caso simplemente comprobaremos si un determinado objeto tiene
definida la anotación `@OracleStruct` para en ese caso realizar su conversión.

CAPTION: faltaría realizar la conversión de tipos de vuelta, así como la de listas de estructuras.

=== Acceso utilizando Spring JDBC

En este caso utilizaremos el objeto `SimpleJdbcCall` del modo siguiente:

[source,java]
----
@Service
@Slf4j
public class ClaimSpringJdbcService implements ClaimService {

  private final SimpleJdbcCall jdbcCall;
  private final StructDefinitionService definitionService;

  public ClaimSpringJdbcService(
      DataSource dataSource,
      StructDefinitionService definitionService) {

    this.definitionService = definitionService;
    jdbcCall = new SimpleJdbcCall(dataSource)
      .withProcedureName("MPG_K_EX_SINIESTRO_ACCIDENTE.PR_PROCESA_PETICION")
      .withCatalogName("MPD_LD")
            .withoutProcedureColumnMetaDataAccess()
            .useInParameterNames("P_R_SINIESTRO_ACC")
      .declareParameters(
        new SqlParameter("P_R_SINIESTRO_ACC", OracleTypes.STRUCT, "T_R_SINIESTRO_ACC"),
        new SqlOutParameter("O_NUM_EXPEDIENTE", Types.VARCHAR),
        new SqlOutParameter("O_COD_ERROR", Types.VARCHAR),
        new SqlOutParameter("O_TXT_ERROR", Types.VARCHAR)
      );
  }

  @Override
  @SuppressWarnings("rawtypes")
  public OSinAccOutS execute(OSinAccInS claim) {
    ...
  }
}
----

////
La implementación que provee _spring-oracle_ es _BeanPropertyStructMapper_ sobre la que se han hecho algunos cambios:

* Conversión recursiva (para que tenga en cuenta la conversión a `STRUCT` en los argumentos de entrada con entidades con anidamiento).
* Almacenamiento en memoria de los descriptores de los tipos. Esto se realiza dado que cada vez que se realiza una transformación se ha de suministrar esa
  información que puede obtenerse haciendo una consulta a Oracle. Esto no es nada óptimo cuando por ejemplo se tienen que convertir gran número de entidades,
  de modo que dado que los tipos de Oracle no cambian entre ejecuciones se pueden almacenar ahorrando por ello gran número de conexiones a Oracle. 


La implementación de Spring está basada en la API de _java.reflect_ y podría ser mejorada bastante con alguna herramienta que nos permita definir la meta-data
necesaria para realizar las conversiones (por ejemplo anotaciones, declaración programática, etc).







----
CREATE OR REPLACE package body MPD_LD.MPG_K_EX_SINIESTRO_ACCIDENTE is
  PROCEDURE PR_PROCESA_PETICION (P_R_SINIESTRO_ACC IN  T_R_SINIESTRO_ACC,
                  O_NUM_EXPEDIENTE  OUT VARCHAR2,
                  O_COD_ERROR       OUT VARCHAR2,
                  O_TXT_ERROR       OUT VARCHAR2) IS
  BEGIN
    O_NUM_EXPEDIENTE := dbms_random.random;
  END;
END MPG_K_EX_SINIESTRO_ACCIDENTE;
----

////

== Referencias

* https://github.com/spring-projects/spring-data-jdbc-ext[Spring Data JDBC Extensions for the Oracle database]
* http://markchensblog.blogspot.com/2015/03/use-spring-simplejdbccall-to-invoke.html
* http://forum.spring.io/forum/spring-projects/data/74391-simplejdbccall-to-call-oracle-function-returning-ref-cursor
* https://docs.spring.io/spring/docs/2.5.x/reference/jdbc.html#jdbc-simple-jdbc-call-1

// * https://github.com/spring-projects/spring-data-jdbc-ext/blob/master/spring-data-oracle/src/main/java/org/springframework/data/jdbc/support/oracle/BeanPropertyStructMapper.java