package org.lab.samples.oracle.model.claim;

import java.io.Serializable;

import lombok.Data;

/**
 * File generated by the Plugin MAPFRE iPL2WS of GAIA - Ver. 3.1.0 - 05/06/2017
 */
@Data
public class OCorresExpdteS implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * email Property
	 */
	private OEmailS email;

	/**
	 * tipovia Property
	 */
	private String tipoVia;

	/**
	 * nomvia Property
	 */
	private String nomVia;

	/**
	 * numero Property
	 */
	private String numero;

	/**
	 * portal Property
	 */
	private String portal;

	/**
	 * esc Property
	 */
	private String esc;

	/**
	 * piso Property
	 */
	private String piso;

	/**
	 * puerta Property
	 */
	private String puerta;

	/**
	 * localidad Property
	 */
	private String localidad;

	/**
	 * codpostal Property
	 */
	private String codPostal;

	/**
	 * codpais Property
	 */
	private String codPais;

	/**
	 * apartado Property
	 */
	private String apartado;

	/**
	 * nomdest Property
	 */
	private String nomDest;

}