package org.lab.samples.pljpa.model;

import java.io.Serializable;

import lombok.Data;

/**
 * File generated by the Plugin MAPFRE iPL2WS of GAIA - Ver. 3.1.0 - 05/06/2017
 */
@Data
public class OEmailS implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * correo Property
	 */
	private String correo;

	/**
	 * codcorresponde Property
	 */
	private String codCorresponde;

	/**
	 * observaciones Property
	 */
	private String observaciones;

}