package org.lab.samples.oracle.model.participant.claim;

import java.io.Serializable;

import lombok.Data;

/**
 * File generated by the Plugin MAPFRE iPL2WS of GAIA - Ver. 3.1.0 - 05/06/2017
 */
@Data
public class ODescripcionS implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * descripcion Property
	 */
	private String descripcion;

}