package org.lab.samples.oracle.model.participant.claim;

import java.io.Serializable;

import lombok.Data;

/**
 * File generated by the Plugin MAPFRE iPL2WS of GAIA - Ver. 3.1.0 - 05/06/2017
 */
@Data
public class OFederacionS implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * nombre Property
	 */
	private String nombre;

	/**
	 * apellidos Property
	 */
	private String apellidos;

	/**
	 * domicilio Property
	 */
	private String domicilio;

	/**
	 * localidad Property
	 */
	private String localidad;

	/**
	 * codpostal Property
	 */
	private String codPostal;

	/**
	 * dni Property
	 */
	private String dni;

	/**
	 * telef1 Property
	 */
	private String telef1;

	/**
	 * telef2 Property
	 */
	private String telef2;

	/**
	 * licencia Property
	 */
	private String licencia;

	/**
	 * club Property
	 */
	private String club;

	/**
	 * tclub Property
	 */
	private String tclub;

	/**
	 * telclub Property
	 */
	private String telClub;

	/**
	 * atendido Property
	 */
	private String atendido;

	/**
	 * cliatendido Property
	 */
	private String cliAtendido;

	/**
	 * clirecomendada Property
	 */
	private String cliRecomendada;

}