package org.lab.samples.oracle.model;

import java.io.Serializable;
import java.util.List;

import org.lab.samples.oracle.annotation.OracleStruct;

import lombok.Data;

/**
 * File generated by the Plugin MAPFRE iPL2WS of GAIA - Ver. 3.1.0 - 05/06/2017
 */
@Data
@OracleStruct("O_ACCIDENTE_S")
public class OAccidenteS implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * nomdecla Property
	 */
	private String nomDecla;

	/**
	 * apeldecla Property
	 */
	private String apelDecla;

	/**
	 * tfnodecla Property
	 */
	private String tfnoDecla;

	/**
	 * relacion Property
	 */
	private String relacion;

	/**
	 * nomaccidentado Property
	 */
	private String nomAccidentado;

	/**
	 * apelaccidentado Property
	 */
	private String apelAccidentado;

	/**
	 * tfnoaccidentado Property
	 */
	private String tfnoAccidentado;

	/**
	 * domaccidentado Property
	 */
	private String domAccidentado;

	/**
	 * locaccidentado Property
	 */
	private String locAccidentado;

	/**
	 * distaccidentado Property
	 */
	private String distAccidentado;

	/**
	 * lugarocur Property
	 */
	private String lugarOcur;

	/**
	 * horaocur Property
	 */
	private String horaOcur;

	/**
	 * formaocur Property
	 */
	private List<ODescripcionS> formaOcur;

	/**
	 * causante Property
	 */
	private OCausanteS causante;

	/**
	 * clirecomendada Property
	 */
	private String cliRecomendada;

	/**
	 * danosterceros Property
	 */
	private List<ODescripcionS> danosTerceros;

	/**
	 * polizas Property
	 */
	private List<ODescripcionS> polizas;

	/**
	 * fallecimiento Property
	 */
	private String fallecimiento;

	/**
	 * clinicas Property
	 */
	private List<ODescripcionS> clinicas;

	/**
	 * tratamiento Property
	 */
	private String tratamiento;

	/**
	 * ingresado Property
	 */
	private String ingresado;

	/**
	 * clirecomendada2 Property
	 */
	private String cliRecomendada2;

	/**
	 * lesiones Property
	 */
	private List<ODescripcionS> lesiones;

	/**
	 * bajalabor Property
	 */
	private String bajaLabor;

	/**
	 * dias Property
	 */
	private String dias;

	/**
	 * localizacion Property
	 */
	private String localizacion;

	/**
	 * localiact Property
	 */
	private String localiAct;

	/**
	 * localpostal Property
	 */
	private String localPostal;

	/**
	 * localtfno Property
	 */
	private String localTfno;

}