package org.lab.samples.oracle.model;

import java.io.Serializable;

import lombok.Data;

/**
 * File generated by the Plugin MAPFRE iPL2WS of GAIA - Ver. 3.1.0 - 05/06/2017
 */
@Data
public class OComunicanteS implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * nombre Property
	 */
	private String nombre;

	/**
	 * apellidos Property
	 */
	private String apellidos;

	/**
	 * telefono Property
	 */
	private String telefono;

	/**
	 * codrelacion Property
	 */
	private String codRelacion;

}